# most of the config is in the conf.d/ directory,
# as I prefer to organise it into different files

if status is-interactive
    # echo
end

# opam configuration (autogenerated)
test -r "$HOME/.opam/opam-init/init.fish" \
    && source "$HOME/.opam/opam-init/init.fish" > /dev/null 2> /dev/null; or true

fish_add_path $HOME/.local/share/coursier/bin
